# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM registry.fly.io/sidecar:deployment-01JT24ECEX1GA2W2G8NTXF2ZYS as sidecar_image

# User's Dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies without running prepare scripts to avoid premature build
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source files
COPY . .

# Build TypeScript
RUN npm run build

# Default command to run MCP server
CMD ["node", "dist/index.js"]
# End user Dockerfile

# Integrate Smithery Gateway
COPY --from=sidecar_image /app/gateway-app-glibc /tmp/smithery-gateway-glibc
COPY --from=sidecar_image /app/gateway-app-musl /tmp/smithery-gateway-musl

USER root

# Install required libraries for Alpine
RUN /bin/sh -c 'set -eux &&   if grep -q "Alpine" /etc/os-release 2>/dev/null; then     echo "Alpine Linux detected, installing required libraries" &&     apk add --no-cache libstdc++ libgcc &&     echo "musl" > /tmp/os-family;     exit 0;   fi'

# Detect OS family fallback
RUN /bin/sh -c 'set -eux &&   if [ -f /tmp/os-family ]; then     exit 0;   fi &&   shell_to_check="/bin/sh" &&   if [ ! -x "$shell_to_check" ]; then     shell_to_check="/usr/bin/env";   fi &&   if ! command -v ldd >/dev/null 2>&1; then     echo "ERROR: ldd not found in the user image. Cannot detect OS family." >&2 &&     exit 1;   fi &&   if ldd "$shell_to_check" 2>&1 | grep -qi musl; then     echo "musl detected" &&     echo "musl" > /tmp/os-family;   else     echo "glibc detected" &&     echo "glibc" > /tmp/os-family;   fi'

# Pick the correct gateway binary
RUN /bin/sh -c 'set -eux &&   os_family="$(cat /tmp/os-family)" &&   case "$os_family" in     musl) mv /tmp/smithery-gateway-musl /usr/local/bin/smithery-gateway ;;     glibc) mv /tmp/smithery-gateway-glibc /usr/local/bin/smithery-gateway ;;     *) echo "Unknown OS family: $os_family" >&2 && exit 1 ;;   esac &&   chmod +x /usr/local/bin/smithery-gateway &&   rm -f /tmp/smithery-gateway-*'

EXPOSE 8080

# Use Smithery Gateway as the entrypoint
ENTRYPOINT ["/usr/local/bin/smithery-gateway"]
CMD ["--port", "8080", "--configb64", ""]
